services:
  backend:
    build:
      context: .
      dockerfile: Backend-Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - ./app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/vite.config.js:/app/vite.config.js
    environment:
      - VITE_API_URL=
    depends_on:
      - backend
